AUTOMAKE_OPTIONS = foreign

systemdsystemunitdir = @systemdsystemunitdir@

systemdsystemunit_DATA = \
	spmd.service spmd.socket \
	iked.service iked.socket \
	kinkd.service \
	racoon2.target

EXTRA_DIST = \
	spmd.service.in spmd.socket.in \
	iked.service.in iked.socket.in \
	kinkd.service.in \
	racoon2.target.in
